`define MODULE_NAME FFT_Top
`define TARGET_DEVICE_GW2A_18
`define FIXED
`define FFT64
`define POINTS 64
`define POINTS_LOG 6
`define LOW_RESOURCE
`define MODE_INVERSE
`define OUTPUT_NATURAL
`define SCALING_RS111
`define INPUT_DATA_WIDTH 32
`define INPUT_DATA_WIDTH_LOG 5
`define TWIDDLE_FACTOR_WIDTH 16
`define TWIDDLE_FACTOR_WIDTH_LOG 4
`define OUTPUT_DATA_WIDTH 32
`define OUTPUT_DATA_WIDTH_LOG 5
`define REDUCTION_TRUNCATION
`define DSP_BLOCK_BASED
`define EBR_MEMORY
`define TDF_EBR_MEMORY
